### PR TITLE
Fix NLPBlockDualStart and tidy MOI tests

### LINKED ISSUE #233: Fix excluded tests in MOI
There are a large number of tests in MOI that are excluded:

https://github.com/jump-dev/KNITRO.jl/blob/c77bd0f30ac9e2e8c7950db005c34d3da9fe92f2/test/MOI_wrapper.jl#L44-L59

This is generally a sign that there are bugs in the interface that need fixing.

We should also try the tests without a caching optimizer, which will expose a lot more problems.

### LINKED ISSUE #250: MOI.set(model::Optimizer, ::MOI.NLPBlockDualStart, values) does not work
I am trying to use `JuMP.set_nonlinear_dual_start_value` to set the initial values for duals, but it doesn't work because it seems like [`MOI.set(model::Optimizer, ::MOI.NLPBlockDualStart, values)`](https://github.com/jump-dev/KNITRO.jl/blob/4c56de7684c42dd3c83c5fbc515ae1f424eed524/src/MOI_wrapper/nlp.jl#LL39C1-L39C1) is left unfixed since fb1b4d5. If we replaced the body with something like `KN_set_con_dual_init_values(model.inner, length(model.nlp_index_cons), model.nlp_index_cons, values)`, would it work?

### PR DESCRIPTION
**Pull request by odow**
Closes #233
Closes #250

### CODE REVIEW

**Comment by odow** [comment]
Hmm. These passed locally. I need another look

File: test/MOI_wrapper.jl [hunk 1]
```diff
@@ -38,24 +38,19 @@ function test_MOI_Test_cached()
...
-    )
+    model =
+        MOI.instantiate(KNITRO.Optimizer; with_bridge_type=Float64, with_cache_type=Float64)
     MOI.set(model, MOI.Silent(), true)
+    config = MOI.Test.Config(
+        atol=1e-3,
+        rtol=1e-3,
+        optimal_status=MOI.LOCALLY_SOLVED,
+        infeasible_status=MOI.LOCALLY_INFEASIBLE,
+        exclude=[MOI.VariableBasisStatus, MOI.ConstraintBasisStatus],
```
Comment (odow) [inline test/MOI_wrapper.jl:49]:
```suggestion
        exclude=Any[MOI.VariableBasisStatus, MOI.ConstraintBasisStatus],
```
