### PR TITLE
A large refactor to get the tests passing

### LINKED ISSUE #231: SYSTEM: show(lasterr) caused an error
I was trying to use KNITRO with MOI, and I tested this example [here](https://jump.dev/MathOptInterface.jl/stable/tutorials/example/) using KNITRO.jl.
I tried a Cutting Plane method, so after optimizing the model, I added the constraint below
`MOI.add_constraint(optimizer,x[1],MathOptInterface.LessThan{Float64}(0.0));`
And this caused the error: `SYSTEM: show(lasterr) caused an error`
I tried to use GLPK and the code worked with it.
Here is the code that I used
```
using MathOptInterface
const MOI = MathOptInterface
using KNITRO
optimizer = KNITRO.Optimizer()
c = [1.0, 2.0, 3.0]
w = [0.3, 0.5, 1.0]
C = 3.2
x = MOI.add_variables(optimizer, length(c));
MOI.set(
           optimizer,
           MOI.ObjectiveFunction{MOI.ScalarAffineFunction{Float64}}(),
           MOI.ScalarAffineFunction(MOI.ScalarAffineTerm.(c, x), 0.0),
       );
MOI.set(optimizer, MOI.ObjectiveSense(), MOI.MAX_SENSE)
MOI.add_constraint(
           optimizer,
           MOI.ScalarAffineFunction(MOI.ScalarAffineTerm.(w, x), 0.0),
           MOI.LessThan(C),
       );
for x_i in x
    MOI.add_constraint(optimizer, x_i, MOI.ZeroOne())
end
MOI.optimize!(optimizer)
MOI.add_constraint(optimizer,x[1],MathOptInterface.LessThan{Float64}(0.0)); # ERROR
MOI.optimize!(optimizer)
MOI.get(optimizer, MOI.VariablePrimal(), x)
```
And here is the log
```
=======================================
           Academic License
       (NOT FOR COMMERCIAL USE)
         Artelys Knitro 12.4.0
=======================================

No start point provided -- Knitro computing one.

datacheck:               0
hessian_no_f:            1
The problem is identified as an MILP.
Knitro changing mip_method from AUTO to 1.
Knitro changing mip_rootalg from AUTO to 1.
Knitro changing mip_lpalg from AUTO to 3.
Knitro changing mip_nodealg from AUTO to 3.
Knitro changing mip_branchrule from AUTO to 2.
Knitro changing mip_selectrule from AUTO to 2.
Knitro changing mip_mir from AUTO to 0.
Knitro changing mip_rounding from AUTO to 3.
Knitro changing mip_heuristic_strategy from AUTO to 1.
Knitro changing mip_heuristic_feaspump from AUTO to 1.
Knitro changing mip_heuristic_mpec from AUTO to 0.
Knitro changing mip_heuristic_diving from AUTO to 0.
Knitro changing mip_pseudoinit from AUTO to 1.

Problem Characteristics
-----------------------
Objective goal:  Maximize
Objective type:  linear
Number of variables:                                  3
    bounded below only:                               0
    bounded above only:                               0
    bounded below and above:                          3
    fixed:                                            0
    free:                                             0
Number of binary variables:                           3
Number of integer variables:                          0
Number of constraints:                                1
    linear equalities:                                0
    quadratic equalities:                             0
    gen. nonlinear equalities:                        0
    linear one-sided inequalities:                    1
    quadratic one-sided inequalities:                 0
    gen. nonlinear one-sided inequalities:            0
    linear two-sided inequalities:                    0
    quadratic two-sided inequalities:                 0
    gen. nonlinear two-sided inequalities:            0
Number of nonzeros in Jacobian:                       3
Number of nonzeros in Hessian:                        0

Knitro detected 0 GUB constraints
Knitro derived 0 knapsack covers after examining 1 constraint
Knitro solving root node relaxation

   Node    Left    Iinf     Objective         Best Relaxatn  Best Incumbent
  ------  ------  ------  --------------     --------------  --------------
*      1       0       0    6.000000e+00       6.000000e+00    6.000000e+00

EXIT: Optimal solution found.

Final Statistics for MIP
------------------------
Final objective value               =   6.00000000000000e+00
Final integrality gap (abs / rel)   =  0.00e+00 /   0.00e+00 ( 0.00%)
# of nodes processed                =        1
# of subproblems processed          =        2
# of LP iterations                  =        0
Total program time (secs)           =       0.006 (     0.016 CPU time)
Time spent in evaluations (secs)    =       0.000

===========================================================================

SYSTEM: show(lasterr) caused an error

Stacktrace:
 [1] add_constraint(model::KNITRO.Optimizer, vi::MathOptInterface.VariableIndex, lt::MathOptInterface.LessThan{Float64})
   @ KNITRO C:\Users\gabponte\.julia\packages\KNITRO\6cfYO\src\MOI_wrapper\constraints.jl:150
 [2] top-level scope
   @ In[3]:24
 [3] eval
   @ .\boot.jl:373 [inlined]
 [4] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base .\loading.jl:1196
```

### PR DESCRIPTION
**Pull request by odow**
This is probably going to be a lot of work, by the looks of the
number of failing tests.

Here's the list of current failures
```
    test_conic_GeometricMeanCone_VectorAffineFunction                          |   10     2            12
    test_conic_GeometricMeanCone_VectorAffineFunction_2                        |   11     2            13
    test_conic_GeometricMeanCone_VectorOfVariables                             |   10     2            12
    test_conic_GeometricMeanCone_VectorOfVariables_2                           |   11     2            13
    test_conic_RotatedSecondOrderCone_INFEASIBLE_2                             |   26     3      4     33
    test_conic_RotatedSecondOrderCone_VectorAffineFunction                     |    9            2     11
    test_conic_RotatedSecondOrderCone_VectorOfVariables                        |   17            2     19
    test_conic_RotatedSecondOrderCone_out_of_order                             |   12     1            13
    test_conic_SecondOrderCone_Nonnegatives                                    |   13     4            17
    test_conic_SecondOrderCone_Nonpositives                                    |   13     4            17
    test_conic_SecondOrderCone_VectorAffineFunction                            |   15     2            17
    test_conic_SecondOrderCone_VectorOfVariables                               |   15     2            17
    test_conic_SecondOrderCone_out_of_order                                    |   10     2            12
    test_constraint_PrimalStart_DualStart_SecondOrderCone                      |    6            2      8
```

Closes #231. I replaced the errors with their MOI equivalents.

### CODE REVIEW

**Comment by frapac** [comment]
That does not surprise me. 

1. The MOI wrapper has not been really updated since the original development in Januay 2019. Back then the testing was less exhaustive than it is today, and a lot of mistakes I made has not been caught for that reason. 
2. Let me know if you need help updating the wrapper. I have some time this week, and I would be happy to give you a hand on this.

**Comment by odow** [comment]
I got things working, with the exception of #201.

I removed a bunch of support for constraint types that aren't natively supported like `VectorAffineFunction-in-Nonnegatives`, so the next release will be breaking.

**Comment by odow** [comment]
We're still missing a buuuuuunch of features if we don't use a CachingOptimizer, like `is_valid` for indices, `ListOfConstraints` `ListOfConstraintTypesPresent`, etc. I'm moderately surprised things are even working at all.

File: src/MOI_wrapper/complementarity.jl [hunk 1]
```diff
@@ -3,73 +3,14 @@
...
-# Complementarity constraints (M x + b  complements x)
-# As Knitro supports only complementarity constraints between variables,
-# we reformulate it by adding auxiliary variables:
-#
-# x_aux = Mx + b
-# (x_aux complements x)
-
-MOI.supports_constraint(::Optimizer, ::Type{VAF}, ::Type{MOI.Complements}) = true
-
-function MOI.add_constraint(
```
Comment (frapac) [inline src/MOI_wrapper/complementarity.jl:15]: Why are we removing this function here?

Comment (odow) [reply src/MOI_wrapper/complementarity.jl:15]: Because KNITRO doesn't actually support VectorAffineFunction-in-Complements. We should only implement the constraints we support. Bridges can convert from VectorAffineFunction to VectorOfVariables by adding slacks.

Comment (frapac) [reply src/MOI_wrapper/complementarity.jl:15]: ok

**Comment by odow** [comment]
Perhaps I'll merge this so we can keep attacking in smaller chunks.
